# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HelloMarsTest
                                 A QGIS plugin
 This a test plugin.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-03
        copyright            : (C) 2024 by Ing. Campos Murguía Ángel Ariel
        email                : ing.campos.m.a.a@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HelloMarsTest class from file HelloMarsTest.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hello_mars_test import HelloMarsTest
    return HelloMarsTest(iface)
